<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\JmaStudio.Hardware\JmaStudio.Hardware.csproj" />
    <ProjectReference Include="..\JmaStudio.Effects\JmaStudio.Effects.csproj" />
    <ProjectReference Include="..\JmaStudio.Presets\JmaStudio.Presets.csproj" />
  </ItemGroup>

</Project>
